### YamlMime:ManagedReference
items:
- uid: MyTrips.Application.Dtos.CreateClientDto
  commentId: T:MyTrips.Application.Dtos.CreateClientDto
  id: CreateClientDto
  parent: MyTrips.Application.Dtos
  children:
  - MyTrips.Application.Dtos.CreateClientDto.Email
  - MyTrips.Application.Dtos.CreateClientDto.Name
  langs:
  - csharp
  - vb
  name: CreateClientDto
  nameWithType: CreateClientDto
  fullName: MyTrips.Application.Dtos.CreateClientDto
  type: Class
  source:
    remote:
      path: src/MyTrips.Application/Dtos/CreateClientDto.cs
      branch: main
      repo: https://github.com/filimor/api-ploomes.git
    id: CreateClientDto
    path: ../../src/MyTrips.Application/Dtos/CreateClientDto.cs
    startLine: 2
  assemblies:
  - MyTrips.Application
  namespace: MyTrips.Application.Dtos
  syntax:
    content: public class CreateClientDto
    content.vb: Public Class CreateClientDto
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: MyTrips.Application.Dtos.CreateClientDto.Name
  commentId: P:MyTrips.Application.Dtos.CreateClientDto.Name
  id: Name
  parent: MyTrips.Application.Dtos.CreateClientDto
  langs:
  - csharp
  - vb
  name: Name
  nameWithType: CreateClientDto.Name
  fullName: MyTrips.Application.Dtos.CreateClientDto.Name
  type: Property
  source:
    remote:
      path: src/MyTrips.Application/Dtos/CreateClientDto.cs
      branch: main
      repo: https://github.com/filimor/api-ploomes.git
    id: Name
    path: ../../src/MyTrips.Application/Dtos/CreateClientDto.cs
    startLine: 4
  assemblies:
  - MyTrips.Application
  namespace: MyTrips.Application.Dtos
  syntax:
    content: public string Name { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Name As String
  overload: MyTrips.Application.Dtos.CreateClientDto.Name*
- uid: MyTrips.Application.Dtos.CreateClientDto.Email
  commentId: P:MyTrips.Application.Dtos.CreateClientDto.Email
  id: Email
  parent: MyTrips.Application.Dtos.CreateClientDto
  langs:
  - csharp
  - vb
  name: Email
  nameWithType: CreateClientDto.Email
  fullName: MyTrips.Application.Dtos.CreateClientDto.Email
  type: Property
  source:
    remote:
      path: src/MyTrips.Application/Dtos/CreateClientDto.cs
      branch: main
      repo: https://github.com/filimor/api-ploomes.git
    id: Email
    path: ../../src/MyTrips.Application/Dtos/CreateClientDto.cs
    startLine: 5
  assemblies:
  - MyTrips.Application
  namespace: MyTrips.Application.Dtos
  syntax:
    content: public string Email { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Email As String
  overload: MyTrips.Application.Dtos.CreateClientDto.Email*
references:
- uid: MyTrips.Application.Dtos
  commentId: N:MyTrips.Application.Dtos
  href: MyTrips.html
  name: MyTrips.Application.Dtos
  nameWithType: MyTrips.Application.Dtos
  fullName: MyTrips.Application.Dtos
  spec.csharp:
  - uid: MyTrips
    name: MyTrips
    href: MyTrips.html
  - name: .
  - uid: MyTrips.Application
    name: Application
    href: MyTrips.Application.html
  - name: .
  - uid: MyTrips.Application.Dtos
    name: Dtos
    href: MyTrips.Application.Dtos.html
  spec.vb:
  - uid: MyTrips
    name: MyTrips
    href: MyTrips.html
  - name: .
  - uid: MyTrips.Application
    name: Application
    href: MyTrips.Application.html
  - name: .
  - uid: MyTrips.Application.Dtos
    name: Dtos
    href: MyTrips.Application.Dtos.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: MyTrips.Application.Dtos.CreateClientDto.Name*
  commentId: Overload:MyTrips.Application.Dtos.CreateClientDto.Name
  href: MyTrips.Application.Dtos.CreateClientDto.html#MyTrips_Application_Dtos_CreateClientDto_Name
  name: Name
  nameWithType: CreateClientDto.Name
  fullName: MyTrips.Application.Dtos.CreateClientDto.Name
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: MyTrips.Application.Dtos.CreateClientDto.Email*
  commentId: Overload:MyTrips.Application.Dtos.CreateClientDto.Email
  href: MyTrips.Application.Dtos.CreateClientDto.html#MyTrips_Application_Dtos_CreateClientDto_Email
  name: Email
  nameWithType: CreateClientDto.Email
  fullName: MyTrips.Application.Dtos.CreateClientDto.Email
